### ISSUE TITLE
Windows DLL Weirdness

### ISSUE THREAD

**Issue by polm** [polm/fugashi#33]
Sometimes this error happens on Windows:

    ImportError: DLL load failed while importing fugashi: the specified module could not be found

From experience, this can always be fixed by **using a virtualenv**. If you use a virtualenv and it does not work, please let me know. Using a virtualenv is the officially recommended workaround. Other environment managers should also work.

Normally when this happens, the dll has been installed, but Python is not looking in the right path for it. You can copy it to the right path to fix it, but I would recommend using a virtualenv instead.

The current status of this issue (2024-11-13) is that I cannot reproduce it, and I do not know what steps can be taken, if any, to prevent it from happening at the package level.

What follows is how I have tried to investigate this.

- Asked pip devs https://github.com/pypa/pip/issues/10605: They indicated that the way I am packaging the dll is wrong, but are not sure what the right thing is, and did not have a concrete suggestion.
- Asked setuptools devs https://github.com/pypa/setuptools/discussions/2830: I got one response saying people don't normally package DLLs, but no recommendation on what to do.
- See issues tagged https://github.com/polm/fugashi/labels/missing-dll, also [in the mecab-python3 repo]( https://github.com/SamuraiT/mecab-python3/labels/missing-dll)

In order to resolve this issue, I will need either:

1. a process I can use to reproduce it OR
2. cooperation from someone experiencing the issue

Ideally I would be able to test it myself, but if that is difficult, someone who has the issue and can test new package builds would be a big help.

-----

*What follows is the original text of this issue from 2021.*

Via email I have a report of a Windows user who installed fugashi via pip without errors, but didn't get `libmecab.dll` in their `site-packages/fugashi` directory, which led to errors at import time like this:

    ImportError: DLL load failed while importing fugashi: the specified module could not be found

For what it's worth, the dll is definitely in the wheel file, and when I install it on Windows the dll ends up in the `site-packages/fugashi` package as expected.

This thread has some info on DLLs and Python on Windows:

https://github.com/Toblerity/Fiona/issues/851

One thing that we could potentially do is check for ImportErrors, and if the code is being executed on Windows, check if `libmecab.dll` is present and give a very specific error if not. On the other hand, since it's not clear how this happened in the first place, maybe just having an FAQ entry (or this issue) is enough for now.

**Comment by kinow** [comment]
Tested on my Win 10 pro, with Python 3.9 (from Windows Store) and a venv. Worked with no issues, both with or without `wheel` package 👍

**Comment by polm** [comment]
Closing because no action is required for the time being.

**Comment by alinacoding** [comment]
I also encountered this error while using Python 3.8 (from Windows Store). Where can I find the fugashi DLL to manually download it?

**Comment by polm** [comment]
@alinacoding You can download it from PyPI. 

https://pypi.org/project/fugashi/#files

Can you explain how you installed fugashi? Did you use pip, was it in Powershell or something else, etc. This really shouldn't happen so any hints are helpful.

**Comment by polm** [comment]
Note that maybe installing in a venv works, but installing globally does not. Not really sure though. (In general I would recommend always using venvs.)

**Comment by alinacoding** [comment]
I used pip to install it on a Windows 64-bit machine, after I got the following error trace:
Traceback (most recent call last):
  File "chatbot.py", line 341, in <module>
    main()
  File "chatbot.py", line 292, in main
    bjsa = BertJapaneseSentimentAnalyzer()
  File "chatbot.py", line 48, in __init__
    self.tokenizer = BertJapaneseTokenizer.from_pretrained('cl-tohoku/bert-base-japanese-whole-word-masking')
  File "C:\Users\avoic\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\transformers\tokenization_utils_base.py", line 1719, in from_pretrained
    return cls._from_pretrained(
  File "C:\Users\avoic\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\transformers\tokenization_utils_base.py", line 1792, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "C:\Users\avoic\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\transformers\models\bert_japanese\tokenization_bert_japanese.py", line 151, in __init__
    self.word_tokenizer = MecabTokenizer(
  File "C:\Users\avoic\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\transformers\models\bert_japanese\tokenization_bert_japanese.py", line 231, in __init__
    import fugashi
  File "C:\Users\avoic\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fugashi\__init__.py", line 1, in <module>
    from .fugashi import *
ImportError: DLL load failed while importing fugashi: The specified module could not be found.

On a Ubuntu 16.04 64-bit machine the installation via pip went smoothly.
On Windows I am also having trouble installing the mecab-python-windows package, since it complains about missing mecab.h file.

Thank you for your suggestion, I will try using a venv.

**Comment by polm** [comment]
Thanks for the extra info! It definitely looks like pip is just being weird, no idea why that would happen.

> On Windows I am also having trouble installing the mecab-python-windows package, since it complains about missing mecab.h file.

That package is not maintained - the author moved development to `mecab` on PyPI. They mention the error you saw in their announcement post [here](https://qiita.com/yukinoi/items/990b6933d9f21ba0fb43). In general there is not much difference between their package and mecab-python3 except that mecab-python3 includes the MeCab binary on all platforms so it shouldn't require an extra install, though that might not help if you keep having this pip issue.

**Comment by Pugnator** [comment]
Have the same issue, installed python 3.12 from the official site, default settings, Windows 10.
The problem is pip installs the mecab.dll into `c:\users\user\appdata\roaming\python\lib\site-packages\fugashi\libmecab.dll`
But the library is checked against `C:\Users\user\AppData\Roaming\Python\Python312\site-packages\fugashi`
If I copy the lib - everything works like a charm.

**Comment by polm** [comment]
Glad you figured it out, and sorry you had to deal with this. 

To be clear, while I still don't understand this very well, as far as I am aware it never happens if you use a virtualenv.

Let me update the top of this ticket to summarize what I know.

**Comment by Pugnator** [comment]
> Glad you figured it out, and sorry you had to deal with this.
> 
> To be clear, while I still don't understand this very well, as far as I am aware it never happens if you use a virtualenv.
> 
> Let me update the top of this ticket to summarize what I know.

While it's easy to reproduce at least in my environment, I'll try to debug the installation this weekend to find out the reason. I'll keep you updated.

**Comment by Chibin** [comment]
> Have the same issue, installed python 3.12 from the official site, default settings, Windows 10.
> The problem is pip installs the mecab.dll together with fugashi into `c:\users\user\appdata\roaming\python\lib\site-packages\fugashi\libmecab.dll`
> But the library is checked against `C:\Users\user\AppData\Roaming\Python\Python312\site-packages\fugashi` during the import from python.
> If I copy the lib - everything works like a charm.

I can confirm that this works.
Thank you for the workaround!

**Comment by polm** [comment]
@Chibin Hello, author of the library here. Sorry you ran into this problem. 

To help me fix this, I want to check something - did you use a virtualenv at any point? That should fix your issue without manual intervention.

**Comment by Chibin** [comment]
> [@Chibin](https://github.com/Chibin) Hello, author of the library here. Sorry you ran into this problem.
> 
> To help me fix this, I want to check something - did you use a virtualenv at any point? That should fix your issue without manual intervention.

Thank you for pointing this out once more.
I'm directly installed in my windows environment.
I did not try virtualenv, but I'll keep this in mind in the future.

**Comment by sabonerune** [comment]
I was able to create a Wheel that works properly on Windows using [`delvewheel`](https://github.com/adang1345/delvewheel).

1. Delete the following line
https://github.com/polm/fugashi/blob/9dcaaa4e03c1c0101645daeeb70a035674fee513/setup.py#L48

2. Build the wheel as usual.
`python -m build .`

3. Add PATH to mecab.
4. Run `delvewheel`.
`python -m delvewheel ./dist/fugashi-*.whl`

5. The modified wheel will be created in the `wheelhouse`.

---

I'm not familiar with other platforms, but I think you should delete the `data_files`.
`data_files` is deprecated and not supposed to work with absolute paths.
https://setuptools.pypa.io/en/latest/references/keywords.html
> DISCOURAGED - This is an advanced feature and it is not intended to work with absolute paths.

In the case of Linux, `auditwheel` handles it, so it doesn't seem to be a problem.
However, on macOS, some workaround is required.
There is a similar tool called [`delocate`](https://github.com/matthew-brett/delocate), so you might want to use that.

**Comment by polm** [comment]
Thank you for the information about delvewheel, I had not seen that before and it looks like it exists to resolve this issue. I will look into using it. 

I remember previously using delocate for OSX builds (see #18), but removed it at some point - I think cibuildwheel either uses it internally or accomplishes the same thing, so it stopped being necessary.

**Comment by sabonerune** [comment]
@polm
I missed it.

Then `auditwheel`/`cibuildwheel` can automatically bundle libmecab into the wheel if it can find it.
